title: Trading Blog
description: >-
  A simple trading blog built with Jekyll.
baseurl: ""
url: "https://joelmrcdo.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
