title: Trading Blog
description: >-
  A simple trading blog built with Jekyll.
baseurl: ""
url: "https://joelmrcdo.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
header_pages:
  - index.md
  - posts.md
  - about.md
  - target-calculator.md
plugins:
  - jekyll-feed
